name: geoff_widgets
description: A modular ambient app for Android tablets with customizable theming
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0

  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI & Theming
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.15
  google_fonts: ^6.3.1

  # Date & Time
  intl: ^0.20.2

  # Weather API
  weather: ^3.1.1

  # Utils
  uuid: ^4.5.1
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/themes/

